specVersion: 1.0.0
name: bifrost-subql
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: This SubQuery project can be use as a starting point for bifrost network
repository: "https://github.com/bifrost-finance/bifrost-subql.git"
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed"
  endpoint: "wss://bifrost-rpc.liebi.com/ws"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 2048000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleSlp
          kind: substrate/BlockHandler