specVersion: 0.2.0
name: bifrost-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/bifrost-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xbac3c4660b5a171ce801fd7ddde50133a36fa03efbde33b9b5139d5b4e659afd'
  endpoint: 'wss://bifrost-rpc.devnet.liebi.com/ws'
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleSlp
          kind: substrate/BlockHandler