specVersion: 1.0.0
name: bifrost-subql
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: This SubQuery project can be use as a starting point for bifrost network
repository: "https://github.com/bifrost-finance/bifrost-subql.git"
schema:
  file: ./schema.graphql
network:
  chainId: "0x262e1b2ad728475fd6fe88e62d34c200abe6fd693931ddad144059b1eb884e5b"
  endpoint: "wss://hk.p.bifrost-rpc.liebi.com/ws"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 631000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleSlp
          kind: substrate/BlockHandler